### ISSUE TITLE
Read URLs from log file for data driven simulation

### ISSUE THREAD

**Issue by wrolf** [tarekziade/boom#57]
Suggestion for enhancement: add option -r to read requests from stdin.

List of requests should contain either a list of URLs, or be an CLF web server log file, with the request lines matching "GET (\S+)" or "HEAD (\S+)" being applied as patths appended to URL specified on command line.

This would allow for trace driven simulations based on actual request pattern from web server log files. If simulation takes same time to run as time log file represents, then server/network are 100% saturated. If it runs in 10% of the time, then it has capacity for 10x more traffic.

**Comment by tarekziade** [comment]
Are you thinking about something like : https://github.com/chromano/apache-log-replay ?

what happens when we have several users ?  should each user replay the requests sequentially ? how long should it wait between two queries ? should it play the log in a loop or just once ?

**Comment by hanleyhansen** [comment]
@wrolf you might be able to emulate the traffic using a `--pre-hook`. It's in the latest version on pypi. Your pre-hook can even read the log script and update the params for boom accordingly.

You can access a global var in your pre-hook function that does everything you need. Here's an example that I did recently.

```python
import random

i = 0


def pre_hook(method, url, options):
    global i
    if i % 3 == 0:
        options['headers']['Authorization'] = 'Token f848c2795880356aabdeacd1a8fabb6bec56b78e8'
    else:
        options['headers']['Authorization'] = "Token {}".format(''.join(random.choice('0123456789abcdef')
                                                                        for c in range(40)))
    i += 1
    return method, url, options
```

Notice how i'm updating the header and incrementing `i` so i can make every 3rd request use a real token but otherwise use a bogus token. You might be able to do something similar by traversing through your log file and updating the `method, url, options` vars returned from the pre-hook accordingly. 

Hope this helps!

**Comment by hanleyhansen** [comment]
Hi @wrolf, does my proposed solution help? If so, let us know so I can close this issue.

**Comment by wrolf** [comment]
apache-log-replay turns out to be exactly what I need. Thanks!

**Comment by hanleyhansen** [comment]
Excellent. Closing this issue.
